CREATE TABLE COMPATIBILIDADE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID BIGINT NOT NULL,
    VAGA_ID BIGINT NOT NULL,

    PORCENTAGEM INT NOT NULL,
    MELHOR BOOLEAN NOT NULL DEFAULT FALSE,
    GERADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_COMPAT_USUARIO
        FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID),

    CONSTRAINT FK_COMPAT_VAGA
        FOREIGN KEY (VAGA_ID) REFERENCES VAGAS(VAGA_ID)
);
